### ISSUE TITLE
FR: Add option to let bindings trickle into derived modes

### ISSUE THREAD

**Issue by mrvdb** [Kungsgeten/selected.el#15]
I use selected in org-mode and now have to repeat the bindings for org-journal-mode.

It would be nice if that would be automatic.

**Comment by Kungsgeten** [comment]
Thanks for the suggestion! Please try if it works with the latest update.

**Comment by mrvdb** [comment]
[Erik Sjöstrand]:
> Thanks for the suggestion! Please try if it works with the 
> latest update.

Yep, works perfectly for me. Thanks!
