### ISSUE TITLE
Region is lost after calling a binding

### ISSUE THREAD

**Issue by angrybacon** [Kungsgeten/selected.el#2]
With the following:

``` emacs-lisp
(use-package selected
  :commands selected-minor-mode
  :bind (:map selected-keymap
              ("<M-left>" . indent-rigidly-left)
              ("<M-right>" . indent-rigidly-right)))
```

I wish I could just keep indenting things, but region is lost.

I guess it has something to do with `indent-rigidly-left/right`. Assuming a `^` in `interactive`'s arguments would fix it, how do I do that from my own files?

``` emacs-lisp
(defun indent-rigidly-right (beg end)
  "Indent all lines between BEG and END rightward by one space."
  (interactive "r")
  (indent-rigidly--pop-undo)
  (indent-rigidly
   beg end
   (if (eq (current-bidi-paragraph-direction) 'right-to-left) -1 1)))
```

**Comment by Kungsgeten** [comment]
The variable `deactivate-mark` needs to be `nil` at the end of the function, otherwise the mark (and thus the selection) will deactivate if the function modifies the buffer (if I've understood correctly). So something like this:

```
(defun selected-indent-right (beg end)
  (interactive "r")
  (indent-rigidly-right beg end)
  (setq deactivate-mark nil))
```

**Comment by angrybacon** [comment]
Works perfect, thanks!
