### ISSUE TITLE
selected-keymap is void

### ISSUE THREAD

**Issue by ejemba** [Kungsgeten/selected.el#5]
Hi

when using the use-package install 
I have an error 

```
Symbol's value as variable is void: selected-keymap
```

What can I do to fix this ?

thanks

**Comment by Kungsgeten** [comment]
Hmm, could you post the code that you put in your `init.el`? Have you installed `selected.el` by downloading it from GitHub or by installing it from MELPA?

**Comment by ejemba** [comment]
Basically, I already have many use-package package installed in my .emacs.
I just install selected.el via use-package this way.

```
(use-package selected
  :commands selected-minor-mode
  :bind (:map selected-keymap
              ("q" . selected-off)
              ("u" . upcase-region)
              ("d" . downcase-region)
              ("w" . count-words-region)
              ("m" . apply-macro-to-region-lines)))
```

When paste this in my init file I have the message `reference to free variable 'selected-keymap'` appearing as a tooltip, 

When I copy/paste the content of selected.el in a scratch file and evaluate it, it works well. But the use-package integration does not seems to work.

**Comment by Kungsgeten** [comment]
I'm not sure, but could it be because `selected.el` isn't in your load-path? Try "ensuring" it in order to download it from MELPA (if MELPA is in your `package-archives`):

```
(use-package selected
  :ensure t
  :commands selected-minor-mode
  :bind (:map selected-keymap
              ("q" . selected-off)
              ("u" . upcase-region)
              ("d" . downcase-region)
              ("w" . count-words-region)
              ("m" . apply-macro-to-region-lines)))
```

**Comment by ejemba** [comment]
All my other use-package were including this ":ensure t" sorry for this
thank you it resolves the issue.
I think you may update the readme.

**Comment by Kungsgeten** [comment]
No problem! I've updated the readme.
