### ISSUE TITLE
selected--on: Wrong type argument: consp, nil

### ISSUE THREAD

**Issue by angrybacon** [Kungsgeten/selected.el#6]
Whenever I try to mark a region with `S-up/right/down/left`, I get the following error:

>     selected--on: Wrong type argument: consp, nil

This makes the first attempt at marking region fail and forces me to press again `up/right/down/left` while maintaining Shift. Apparently the error occurs on `M-x set-mark-command` and when I click somewhere in the buffer (to move point) as well.

Here is my setup:

```elisp
(use-package selected
  :bind (:map selected-keymap ...)
  :config (selected-global-mode))
```

Let me know if you need anything else.

**Comment by Kungsgeten** [comment]
Hmm, I have no idea. Could you try `M-x toggle-debug-on-error` and paste the error log?

**Comment by angrybacon** [comment]
```elisp
Debugger entered--Lisp error: (wrong-type-argument consp nil)
  selected-region-active-mode(1)
  selected--on()
  run-hooks(activate-mark-hook)
  activate-mark(no-tmm)
  set-mark(670)
  push-mark(nil nil t)
  handle-shift-selection()
  call-interactively(next-line nil nil)
  command-execute(next-line)
```

**Comment by Kungsgeten** [comment]
Aah, it should be fixed now. Note to self: when you add new optional functionality, make sure that the old (default) option still works :)

**Comment by angrybacon** [comment]
Works fine, thanks. :-)
