### ISSUE TITLE
C-g (`keyboard-quit`) does not turn off `selected`

### ISSUE THREAD

**Issue by dholm** [Kungsgeten/selected.el#7]
I have a (bad) habit of hitting C-g (`keyboard-quit`) to cancel my current mark.  When `selected-minor-mode` is active and doing this selected will remain on and active until I hit q (`selected-off`).

Would it be possible to turn selected off on `keyboard-quit`?

**Comment by Kungsgeten** [comment]
That's strange. `selected-off` can be used interactively when you want to maintain the selected region, but deactivate the keybindings of `selected`. It is also run in `deactivate-mark-hook`, as long as `selected-minor-mode` is active, so cancelling the mark with `C-g` should run `selected-off` automatically (it does for me).

TL;DR: `selected` should already turn off on `keyboard-quit`, I find it strange that it doesn't for you.

Could you do `C-h v deactivate-mark-hook`, while `selected-minor-mode` is active, and see what is says?

**Comment by dholm** [comment]
```
deactivate-mark-hook is a variable defined in ‘simple.el’.
Its value is (selected-off)

  This variable may be risky if used as a file-local variable.

Documentation:
Hook run when the mark becomes inactive.

```

I also tried to eval `(run-hooks 'deactivate-mark-hook)` with a region selected and got `Wrong type argument: arrayp, nil`.

**Comment by Kungsgeten** [comment]
Hmm, that's strange, it works for me. Could you try `M-x toggle-debug-on-error` and try it again?

**Comment by dholm** [comment]
After restarting Emacs I no longer get `Wrong type argument: arrayp, nil` when evaluating `(run-hooks 'deactivate-mark-hook)`.  However, if I cancel the selection using `C-g` it still doesn't disable `selected`.

I used `edebug-defun` to set a breakpoint in `selected-off` and it doesn't execute when I hit `C-g`, only if I eval `keyboard-quit` in the minibuffer.

**Comment by Kungsgeten** [comment]
That's very strange. And you're sure that you haven't bound `C-g` to something different? For instance if you have bound `C-g` to something in `selected-keymap`?

**Comment by dholm** [comment]
@Kungsgeten Sorry, I totally missed your last reply.  I just found something interesting.  When I have an active selection and `describe-key C-g` it says:

```
C-g runs the command cua-cancel (found in cua--region-keymap), which
is an interactive compiled Lisp function in ‘cua-base.el’.
```

I actually enable `cua-selection-mode` for its rectangle selection enhancements.  I will disable it and see what happens..

**Comment by dholm** [comment]
Ok, with `cua-selection-mode` disabled `selected` works as expected.  So far I have not noticed that I lost any of the features I use when selecting rectangles either so I might just throw cua out completely.

Thanks for the support!
