### ISSUE TITLE
any chance this can work with evil mode?

### ISSUE THREAD

**Issue by zeltak** [Kungsgeten/selected.el#8]
Hi

i started playing today with selected.el and it seems really cool, thx for this!

the problem is that im also an evil user and it seems selected wont really launch when i select text in evil mode. is there any chance these two can work together or thats just not technically possible?

thx!

Z

**Comment by Kungsgeten** [comment]
It probably depends on how Evil mode is implemented. You could try using `(setq selected-minor-mode-override t)` and see if that helps. If it doesn't, I'm not sure what to do.

**Comment by zeltak** [comment]
sweet the over ride trick worked!

thx alot!! if you want i can add it to a wiki if you have such a thing or perhaps you want to add it to the readme?

best

Z

**Comment by Kungsgeten** [comment]
The README sort of mentions it, but I should probably add Evil as an example. I actually wasn't sure if it worked for Evil, so thanks for notifying me :)
