### ISSUE TITLE
selected-keymap doesn't activate if region already active when turning on

### ISSUE THREAD

**Issue by league** [Kungsgeten/selected.el#9]
Hi, I'm using the technique recommended in the ryo-modal README, to synchronize selected-minor-mode with ryo-modal-mode, something like this:

```el
  (defun cl/ryo-sync-selected-mode ()
    (selected-minor-mode (if ryo-modal-mode 1 -1)))
  (add-hook 'ryo-modal-mode-hook 'cl/ryo-sync-selected-mode)
```

But one issue I encountered is that if I already have a region active in "insert" mode (ryo-modal off), and then I hit escape (turning ryo-modal on), the selected keymap doesn't activate and I'm stuck with just the ryo-modal bindings (until I toggle mark off and on again). I guess that's because selected-minor-mode hooks into mark activation/deactivation, but those are removed once out of selected and ryo.

Anyway, it seems to be a one-line fix:

```diff
--- a/selected.el
+++ b/selected.el
@@ -69,6 +69,7 @@
   :lighter " sel"
   (if selected-minor-mode
       (progn
+        (if mark-active (selected--on))
         (add-hook 'activate-mark-hook #'selected--on)
         (add-hook 'deactivate-mark-hook #'selected-off))
     (remove-hook 'activate-mark-hook #'selected--on)
```

which of course I can also do in my hook, but it seems to me like it would be the right thing™ for all users of selected…?

Thanks for both these packages – I gave Evil a fair shake but it wasn't for me, so now I'm having a good time rolling my own!

**Comment by Kungsgeten** [comment]
Thanks! It absolutely makes sense. I'm happy to see that you're enjoying `selected` and `ryo`, even though I'm not using them myself at the moment :)
